### PR TITLE
add register page scaffold + minor fixes in Login page

### LINKED ISSUE #11: Login registration welcome page design is missing
The login, register, and welcome pages currently lack a skeleton layout, which is essential for providing users with visual feedback while the content is loading. Implementing a skeleton layout for these pages will enhance the user experience by indicating that the page is actively loading and reducing perceived load times.

### PR DESCRIPTION
**Pull request by rbakkalian**

### CODE REVIEW

File: frontend/src/pages/Conversation/Discussions/Discussions.tsx [hunk 1]
```diff
@@ -1,7 +1,144 @@
 import Discussion from "./Discussion.tsx";
 
-function Discussions() {
-  return Array.from([1, 2, 3, 4, 5]).map((i) => <Discussion key={i} />);
-}
+const discussions = [
```
Comment (Mgrdich) [inline frontend/src/pages/Conversation/Discussions/Discussions.tsx:3]: this is too much info , but it is okay for now.

File: frontend/src/pages/Conversation/Discussions/Discussion.tsx [hunk 2]
```diff
@@ -1,5 +1,13 @@
...
+interface DiscussionProps {
+  role: "user" | "assistant"; // TODO transform it into object as const enum
+  text: string;
 }
 
-export default Discussion;
+export default function Discussion({ role, text }: DiscussionProps) {
+  return (
+    <div className="flex flex-col">
+      <div className="font-bold">{role === "user" ? "YOU" : "Chatto "}</div>
```
Comment (Mgrdich) [inline frontend/src/pages/Conversation/Discussions/Discussion.tsx]:
```suggestion
      <div className="font-bold">{role === "user" ? "YOU" : "Chatto"}</div>
```

**Review by Mgrdich — APPROVED** [review]
