### PR TITLE
edit title minor fix

### LINKED ISSUE #48: Edit Save persistence is not working correctly.

### PR DESCRIPTION
**Pull request by Yerish26**

### CODE REVIEW

File: backend/src/main/java/com/llm_service/llm_service/service/ConversationService.java [hunk 1]
```diff
@@ -112,8 +113,20 @@ public Conversation editTitle(Conversation conversation, String title) throws Un
...
-        return conversationPersistenceManager.save(
-                conversation.toBuilder().title(title).build(), user.get());
+        return getConversation(conversation, title, user);
+    }
+
+    private Conversation getConversation(Conversation conversation, String title, Optional<User> user) {
+        conversation = Conversation.builder()
+                .id(conversation.getId())
+                .discussions(conversation.getDiscussions())
+                .title((conversationPersistenceManager.save(
```
Comment (Mgrdich) [inline backend/src/main/java/com/llm_service/llm_service/service/ConversationService.java]: persistence save being called here can be misleading since the function name is `getConversation` and we are saving a title inside , persistence save should not be here

**Review by Mgrdich — CHANGES_REQUESTED** [review]

File: backend/src/main/java/com/llm_service/llm_service/service/ConversationService.java (hunk 1 above)
Comment (Yerish26) [reply backend/src/main/java/com/llm_service/llm_service/service/ConversationService.java]: helper method is added

File: backend/src/main/java/com/llm_service/llm_service/service/ConversationService.java [hunk 2]
```diff
@@ -112,8 +113,24 @@ public Conversation editTitle(Conversation conversation, String title) throws Un
...
+                .id(conversation.getId())
+                .discussions(conversation.getDiscussions())
+                .title(getTitle(conversation, title, user))
+                .createdOn(conversation.getCreatedOn())
+                .lastUpdatedOn(Instant.now())
+                .build();
+        return conversation;
+    }
+
+    private String getTitle(Conversation conversation, String title, Optional<User> user) {
```
Comment (Mgrdich) [inline backend/src/main/java/com/llm_service/llm_service/service/ConversationService.java]: this does not solve anything you are just saving in a get method that is not a good behaviour

**Review by Mgrdich — CHANGES_REQUESTED** [review]

**Review by Mgrdich — APPROVED** [review]
